  
  # .github/workflows/az-security-scan.yml

  name: AZ-Security-Scan

on:
  push:
    branches:
      - '*'  # Runs on push to any branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  armourzero_security_test_pre:
    runs-on: ubuntu-latest

    env:
      AZ_API_KEY: "${{ secrets.AZ_TOKEN }}"
      PROJECT_KEY: "${{ secrets.AZ_PROJECT_KEY }}"  # Moved to secrets for security
      BRANCH_NAME: "${{ github.ref_name }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Use latest version for improvements

      - name: Run ArmourZero Security Scan (Pre)
        run: |
          echo "::add-mask::$AZ_API_KEY"
          echo "::add-mask::$PROJECT_KEY"
          docker run -v "$(pwd):/app/wrk" --rm armourzero/pipe-scan:latest \
            --apikey="$AZ_API_KEY" \
            --projectkey="$PROJECT_KEY" \
            --branch="$BRANCH_NAME" \
            --repo="$GITHUB_REPOSITORY"
        continue-on-error: true  # Let workflow continue even if scan fails
